# Generated by Django 4.1.1 on 2022-10-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
