# Generated by Django 4.1.2 on 2022-10-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_profile_image_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/person.png', null=True, upload_to=''),
        ),
    ]
