# Generated by Django 4.1.2 on 2022-10-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
