# Generated by Django 4.1.2 on 2023-01-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quantity',
        ),
    ]
