# Generated by Django 4.1.2 on 2023-01-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_category_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
