# Generated by Django 4.1.2 on 2023-01-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
