# Generated by Django 4.1.2 on 2023-01-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_category_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
    ]
