# Generated by Django 4.1.2 on 2023-02-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_item_rate_remove_item_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rate',
        ),
    ]
