# Generated by Django 4.1.2 on 2023-03-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_staff_alter_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='person.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, default='person.png', null=True, upload_to=''),
        ),
    ]
